site_name: Framework Ar4k by Rossonet
theme:
  name: material
  scheme: slate
  palette:
    primary: deep purple
nav:
    - GUIDA RAPIDA: quick.md
    - Readme progetto: README.md
    - Implementazioni future: TODO.md
    - Licenza: LICENSE.md
    - Doc classi: classi.md
